name: enigo_flutter
description: "一个绑定 rust enigo 的 flutter 插件。"
version: 0.0.1
homepage: https://github.com/GodCount/enigo-flutter

environment:
  sdk: ^3.0.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.7.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true

